version: '3.8'

name: transcendence
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - transcendence
    restart: always
    depends_on:
      - websockets
    ports:
      - "5500:5500"

  websockets:
    container_name: websockets
    build:
      context: backend
      dockerfile: Dockerfile-daphne
    networks:
      - transcendence
    restart: always
    env_file: backend/.env
    ports:
      - "8001:8001"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - transcendence
    restart: always
    env_file: backend/.env
    ports:
      - "8000:8000"
      - "587:587"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: transcendence_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d transcendence_db -U admin" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - transcendence
    expose:
      - "5432"


  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - transcendence
    ports:
      - "6379:6379"

networks:
  transcendence:
    driver: bridge
