# Generated by Django 5.0.4 on 2024-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0014_remove_invitation_room_name_game_allowed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score_player_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_player_2',
            field=models.IntegerField(default=0),
        ),
    ]
