# Generated by Django 5.0.4 on 2024-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0016_remove_game_looser_remove_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
