# Generated by Django 5.0.4 on 2024-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0020_alter_game_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.IntegerField(default=0),
        ),
    ]
