# Generated by Django 5.0.4 on 2024-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0023_tournaments_invitations_incr'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_tournaments',
            field=models.BooleanField(default=False),
        ),
    ]
