# Generated by Django 5.0.4 on 2024-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0026_game_is_finals_game_is_semifinals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Tournaments_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_finals_one', models.CharField(max_length=255)),
                ('semi_finals_two', models.CharField(max_length=255)),
                ('finals', models.CharField(max_length=255)),
            ],
        ),
    ]
