# Generated by Django 5.0.4 on 2024-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0027_name_tournaments_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
