# Generated by Django 5.0.4 on 2024-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0028_game_is_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_tournaments_game',
            name='is_deconnect',
            field=models.BooleanField(default=False),
        ),
    ]
