# Generated by Django 5.0.4 on 2024-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0031_name_tournaments_game_is_connect_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name_tournaments_game',
            name='is_connect_game',
        ),
        migrations.AddField(
            model_name='user',
            name='is_connect_game',
            field=models.BooleanField(default=False),
        ),
    ]
