# Generated by Django 5.0.4 on 2024-05-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0002_remove_user_phone_number_user_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone_number_user',
        ),
    ]
