# Generated by Django 5.0.4 on 2024-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0004_alter_user_profile_photo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='number',
        ),
        migrations.AddField(
            model_name='code',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='code',
            name='otp_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default/42_icon.png', null=True, upload_to='users', verbose_name='Photo de Profile'),
        ),
    ]
