# Generated by Django 5.0.4 on 2024-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0008_revokedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevokedToken',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default/42_icon.png', null=True, upload_to='users/', verbose_name='Photo de Profile'),
        ),
    ]
