# Generated by Django 5.0.4 on 2024-06-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0015_game_score_player_1_game_score_player_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Looser',
        ),
        migrations.RemoveField(
            model_name='game',
            name='Winner',
        ),
    ]
