# Generated by Django 5.0.4 on 2024-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0017_game_player_1_username_game_player_2_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
