# Generated by Django 5.0.4 on 2024-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0019_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_finish',
            field=models.IntegerField(default=0),
        ),
    ]
