# Generated by Django 5.0.4 on 2024-07-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0021_alter_game_is_finish_alter_user_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments_Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('invited_user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations_one_tournaments', to=settings.AUTH_USER_MODEL)),
                ('invited_user_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations_three_tournaments', to=settings.AUTH_USER_MODEL)),
                ('invited_user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations_two_tournaments', to=settings.AUTH_USER_MODEL)),
                ('inviting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
