# Generated by Django 5.0.4 on 2024-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0022_tournaments_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments_invitations',
            name='incr',
            field=models.IntegerField(default=0),
        ),
    ]
