# Generated by Django 5.0.4 on 2024-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0029_name_tournaments_game_is_deconnect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournaments_invit',
            field=models.BooleanField(default=False),
        ),
    ]
