# Generated by Django 5.0.4 on 2024-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0030_user_tournaments_invit'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_tournaments_game',
            name='is_connect_game',
            field=models.BooleanField(default=False),
        ),
    ]
