# Generated by Django 5.0.4 on 2024-07-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0032_remove_name_tournaments_game_is_connect_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_connect_game',
        ),
    ]
