# Generated by Django 5.0.4 on 2024-07-10 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_transcendance', '0033_remove_user_is_connect_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='name_tournaments_game',
            name='allowed_users',
            field=models.ManyToManyField(related_name='Name_Tournaments_Game_finals_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='name_tournaments_game',
            name='authorize_for_finals',
            field=models.ManyToManyField(blank=True, related_name='Name_Tournaments_Game_authorize_finals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='name_tournaments_game',
            name='incr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name_tournaments_game',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
